# Assignment 1
## Finding the Philadelphia ZIP Code with the maximum ZHVI over time

CPLN 620 Data Wrangling  
January 30, 2019  
Jonathan Yuan

In [1]:
import pandas as pd

### Step 1
Load the ZHVI data for each ZIP code, selecting only Philadelphia ZIP codes.

In [2]:
zhvi = pd.read_csv("./data/Zip_Zhvi_AllHomes.csv", engine = 'python')

In [3]:
# query rows that match Philadelphia, PA
phila = zhvi \
    .query('City=="Philadelphia" & State=="PA"') \
    .drop(['RegionID','City','State','Metro','CountyName','SizeRank'],
          axis=1) \
    .rename(index=str, columns={'RegionName': 'ZIPcode'})

phila

,ZIPcode,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,1996-11,1996-12,...,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11
214,19111,84900.0,84700.0,84500.0,84300.0,84200.0,84100.0,83900.0,83800.0,83700.0,...,174300,175500,175700,175800,176400,177300,178400,180300,182800,184800
300,19124,43100.0,43000.0,42900.0,42700.0,42500.0,42400.0,42300.0,42300.0,42300.0,...,86200,88000,88900,89900,90800,91400,91900,92800,94200,95700
377,19120,46100.0,46100.0,46100.0,46100.0,46000.0,45900.0,45900.0,45800.0,45700.0,...,91100,92100,92400,92400,92600,92800,92800,92900,93500,94200
542,19148,41100.0,41100.0,41000.0,40900.0,40700.0,40600.0,40500.0,40400.0,40400.0,...,205700,209500,211800,213400,214900,215500,215700,216900,219800,222500
690,19145,41000.0,41000.0,41000.0,40900.0,40800.0,40700.0,40700.0,40800.0,40900.0,...,204100,208400,209500,209100,209600,211100,212600,213800,215100,216700
700,19146,24800.0,25000.0,25100.0,25100.0,25200.0,25200.0,25100.0,24900.0,24800.0,...,326300,330300,333600,336400,337900,337100,337000,338900,341100,342400
810,19147,61900.0,61500.0,61000.0,60600.0,60100.0,59700.0,59500.0,59500.0,59800.0,...,381100,385400,388000,392300,397800,401200,402500,402800,404200,406600
812,19149,62900.0,62700.0,62500.0,62200.0,61900.0,61700.0,61400.0,61200.0,61100.0,...,136100,138000,139100,140100,141200,142500,144100,145900,147800,149400
970,19103,112700.0,113300.0,113800.0,114300.0,114700.0,115100.0,115600.0,116200.0,117000.0,...,522600,525600,525700,522500,520800,521000,520300,521700,527300,532900
1230,19128,87000.0,87100.0,87200.0,87300.0,87400.0,87400.0,87600.0,87600.0,87700.0,...,241300,242900,243800,244700,245800,246300,246900,248200,250200,252100
1711,19130,71300.0,71300.0,71200.0,71100.0,71000.0,71000.0,70900.0,70800.0,70900.0,...,369800,373100,376200,378600,380800,382100,383400,383900,385700,388200
2070,19115,103100.0,102900.0,102600.0,102200.0,101900.0,101600.0,101400.0,101300.0,101200.0,...,228000,230100,231300,232500,234300,235000,235100,236100,238700,240900
2390,19114,86300.0,86300.0,86100.0,86000.0,85800.0,85600.0,85500.0,85500.0,85500.0,...,194400,197600,199200,199900,200700,201400,202200,203600,205500,206900
2537,19152,87400.0,87300.0,87100.0,86900.0,86700.0,86400.0,86200.0,86000.0,85900.0,...,190700,193600,194900,196300,198800,200900,202200,204300,207200,209600
2700,19141,41100.0,41000.0,41000.0,41000.0,41200.0,41300.0,41400.0,41600.0,41900.0,...,103500,102800,101400,100000,99800,100700,103000,106800,110800,113200
2706,19116,106800.0,106800.0,106900.0,106900.0,107000.0,107000.0,107100.0,107300.0,107600.0,...,229400,231900,233600,235200,237000,238800,241400,243800,246100,248400
2781,19136,66100.0,65900.0,65700.0,65500.0,65400.0,65300.0,65200.0,65200.0,65200.0,...,144800,147000,148000,149400,151400,153500,155700,158000,160100,161600
2883,19138,45700.0,45900.0,46100.0,46200.0,46300.0,46400.0,46500.0,46700.0,46900.0,...,118200,117300,117400,117000,117000,117100,118400,120900,123200,123700
2934,19154,84200.0,84100.0,84100.0,84100.0,84000.0,83900.0,83900.0,83900.0,84000.0,...,207800,209700,210700,211400,212300,213000,213100,213000,213700,214800
2973,19151,58400.0,58300.0,58300.0,58300.0,58200.0,58200.0,58100.0,57900.0,57800.0,...,136100,136200,135900,135800,136400,136800,136700,136700,137300,138500
3077,19135,55600.0,55700.0,55800.0,55800.0,55800.0,55800.0,55800.0,55700.0,55700.0,...,116300,117300,118000,119200,120900,122200,123100,124000,125300,126400
3156,19119,89500.0,89400.0,89300.0,89000.0,88700.0,88400.0,88100.0,87700.0,87500.0,...,256500,260300,263600,267300,271000,273000,273300,272800,273600,275700
3580,19125,32900.0,33100.0,33200.0,33200.0,33300.0,33400.0,33300.0,33300.0,33200.0,...,259900,262000,263200,265100,267400,268600,269400,270900,273200,275200
4050,19142,33500.0,33700.0,33800.0,33800.0,33900.0,34000.0,34100.0,34200.0,34300.0,...,54200,56400,57800,59200,60300,61100,61500,62400,63800,65300
4647,19107,67100.0,66700.0,66200.0,65800.0,65400.0,65100.0,64800.0,64600.0,64700.0,...,300000,300800,301400,301900,301900,301500,302400,303600,307100,312000
4652,19150,64300.0,64300.0,64300.0,64300.0,64400.0,64500.0,64600.0,64900.0,65100.0,...,159300,160400,161300,163200,165700,166600,166500,167600,169500,170700
5051,19122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,187300,193400,195300,197700,200100,201600,203400,206800,211600,215900
5095,19123,65200.0,65000.0,64800.0,64600.0,64500.0,64500.0,64600.0,64700.0,64900.0,...,367400,370500,372900,375900,378500,378500,377700,377500,377200,377200
5584,19106,102000.0,102100.0,102200.0,102400.0,102600.0,103000.0,103400.0,103900.0,104500.0,...,391400,394900,393500,392000,393700,396300,396300,394800,397000,399900
6871,19126,55800.0,55900.0,55800.0,55800.0,55800.0,55800.0,55800.0,55900.0,56100.0,...,146400,146700,147500,150000,152800,154100,156000,158600,160300,161000
7650,19153,68900.0,69000.0,69100.0,69200.0,69300.0,69400.0,69500.0,69700.0,69800.0,...,142700,142800,141900,141700,142400,143000,143200,143600,144600,144700
7679,19129,59500.0,59400.0,59200.0,59000.0,58800.0,58700.0,58500.0,58400.0,58400.0,...,209500,210700,212800,215300,217300,218900,221500,224300,227400,230000
7898,19118,181100.0,181500.0,181900.0,182200.0,182400.0,182700.0,183000.0,183200.0,183600.0,...,515700,518100,525500,531900,536100,541000,546200,550800,555200,559500
8581,19102,79400.0,79500.0,79600.0,79800.0,79900.0,80000.0,80300.0,80500.0,80700.0,...,367300,368400,368400,366500,363400,360200,358800,358800,360200,361400
9237,19127,61900.0,62100.0,62200.0,62300.0,62400.0,62500.0,62500.0,62600.0,62800.0,...,226300,225900,225700,225800,226100,225700,224700,223700,223900,224900
9315,19137,48400.0,48300.0,48200.0,48000.0,47800.0,47600.0,47400.0,47200.0,47000.0,...,150900,151700,151500,152200,154100,155300,155900,157000,159600,162200

### Step 2
Calculate the annual average ZHVI for each ZIP code in Philadelphia and each year.

In [4]:
# pivot ZHVIs to long/tidy format
phila_month = pd.melt(phila,
                      id_vars    = ['ZIPcode'],
                      value_name = 'ZHVI',
                      var_name   = 'Date')

In [5]:
# separate month and year
phila_month = phila_month \
    .assign(Year  = pd.to_datetime(phila_month['Date']).dt.year,
            Month = pd.to_datetime(phila_month['Date']).dt.month) \
    .drop(['Date'], axis = 1) \
    .sort_values(['ZIPcode','Year','Month'])

phila_month

      ZIPcode      ZHVI  Year  Month
33      19102   79400.0  1996      4
69      19102   79500.0  1996      5
105     19102   79600.0  1996      6
141     19102   79800.0  1996      7
177     19102   79900.0  1996      8
213     19102   80000.0  1996      9
249     19102   80300.0  1996     10
285     19102   80500.0  1996     11
321     19102   80700.0  1996     12
357     19102   81200.0  1997      1
393     19102   81600.0  1997      2
429     19102   81900.0  1997      3
465     19102   82200.0  1997      4
501     19102   82500.0  1997      5
537     19102   82800.0  1997      6
573     19102   83200.0  1997      7
609     19102   83500.0  1997      8
645     19102   84000.0  1997      9
681     19102   84400.0  1997     10
717     19102   85000.0  1997     11
753     19102   85700.0  1997     12
789     19102   86600.0  1998      1
825     19102   87500.0  1998      2
861     19102   88300.0  1998      3
897     19102   89300.0  1998      4
933     19102   90300.0  1998      5
969     19102   91400.0  1998      6
1005    19102   92600.0  1998      7
1041    19102   93900.0  1998      8
1077    19102   95200.0  1998      9
...       ...       ...   ...    ...
8730    19154  186100.0  2016      6
8766    19154  188900.0  2016      7
8802    19154  191600.0  2016      8
8838    19154  193000.0  2016      9
8874    19154  193600.0  2016     10
8910    19154  194400.0  2016     11
8946    19154  195100.0  2016     12
8982    19154  195600.0  2017      1
9018    19154  195900.0  2017      2
9054    19154  195400.0  2017      3
9090    19154  194700.0  2017      4
9126    19154  195600.0  2017      5
9162    19154  197200.0  2017      6
9198    19154  198300.0  2017      7
9234    19154  199000.0  2017      8
9270    19154  200600.0  2017      9
9306    19154  202800.0  2017     10
9342    19154  204500.0  2017     11
9378    19154  205300.0  2017     12
9414    19154  206300.0  2018      1
9450    19154  207800.0  2018      2
9486    19154  209700.0  2018      3
9522    19154  210700.0  2018      4
9558    19154  211400.0  2018      5
9594    19154  212300.0  2018      6
9630    19154  213000.0  2018      7
9666    19154  213100.0  2018      8
9702    19154  213000.0  2018      9
9738    19154  213700.0  2018     10
9774    19154  214800.0  2018     11

[9792 rows x 4 columns]

In [6]:
# find the average for each ZIP code in each year
phila_year = phila_month \
    .drop(['Month'], axis = 1) \
    .groupby(['ZIPcode','Year']) \
    .mean() \
    .ZHVI.round() \
    .reset_index()

phila_year

     ZIPcode  Year      ZHVI
0      19102  1996   79967.0
1      19102  1997   83167.0
2      19102  1998   92550.0
3      19102  1999  114358.0
4      19102  2000  145175.0
5      19102  2001  185017.0
6      19102  2002  232733.0
7      19102  2003  277475.0
8      19102  2004  306200.0
9      19102  2005  363100.0
10     19102  2006  375008.0
11     19102  2007  379058.0
12     19102  2008  356275.0
13     19102  2009  352542.0
14     19102  2010  332583.0
15     19102  2011  305283.0
16     19102  2012  300250.0
17     19102  2013  315650.0
18     19102  2014  333817.0
19     19102  2015  329700.0
20     19102  2016  344950.0
21     19102  2017  354625.0
22     19102  2018  363536.0
23     19103  1996  114744.0
24     19103  1997  120983.0
25     19103  1998  130233.0
26     19103  1999  150850.0
27     19103  2000  189225.0
28     19103  2001  246650.0
29     19103  2002  300483.0
..       ...   ...       ...
798    19153  2012  116675.0
799    19153  2013  114542.0
800    19153  2014  116017.0
801    19153  2015  115542.0
802    19153  2016  115375.0
803    19153  2017  125817.0
804    19153  2018  142827.0
805    19154  1996   84022.0
806    19154  1997   84592.0
807    19154  1998   85767.0
808    19154  1999   87192.0
809    19154  2000   90233.0
810    19154  2001   95992.0
811    19154  2002  109833.0
812    19154  2003  130117.0
813    19154  2004  153567.0
814    19154  2005  185742.0
815    19154  2006  201358.0
816    19154  2007  196650.0
817    19154  2008  193592.0
818    19154  2009  188708.0
819    19154  2010  183775.0
820    19154  2011  180700.0
821    19154  2012  178500.0
822    19154  2013  175442.0
823    19154  2014  174100.0
824    19154  2015  171233.0
825    19154  2016  186883.0
826    19154  2017  198742.0
827    19154  2018  211436.0

[828 rows x 3 columns]

### Step 3
Identify the ZIP code with the maximum value for each year

In [7]:
phila_year_max = phila_year \
    .assign(MaxZHVI = phila_year \
                .groupby(['Year'])['ZHVI'] \
                .transform(max)) \
    .query('ZHVI == MaxZHVI') \
    .drop(['ZHVI'], axis = 1) \
    .sort_values(['Year'])

phila_year_max

     ZIPcode  Year   MaxZHVI
184    19118  1996  182400.0
185    19118  1997  184358.0
186    19118  1998  187950.0
187    19118  1999  207350.0
188    19118  2000  239900.0
189    19118  2001  274108.0
190    19118  2002  311075.0
30     19103  2003  353258.0
192    19118  2004  411558.0
193    19118  2005  474808.0
194    19118  2006  489217.0
34     19103  2007  492158.0
35     19103  2008  489900.0
36     19103  2009  497867.0
37     19103  2010  466417.0
199    19118  2011  436083.0
200    19118  2012  425242.0
40     19103  2013  425908.0
41     19103  2014  449225.0
203    19118  2015  472150.0
204    19118  2016  499550.0
205    19118  2017  520167.0
206    19118  2018  535991.0